# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/
#
# pre-commit-hooks -> some basic out-of-the-box hooks for precommit
#   check-executables-have-shebangs -> Checks that non-binary executables have a proper shebang
#   check-case-conflict -> Check for files with names that would conflict on a case-insensitive filesystem
#   trailing-whitespace -> Trims trailing whitespace.
#   end-of-file-fixer -> Makes sure files end in a newline and only a newline.
# 
#   check-json -> Attempts to load all json files to verify syntax.
#   check-toml -> Attempts to load all TOML files to verify syntax.
#   check-xml -> Attempts to load all xml files to verify syntax.
#   check-yaml -> Attempts to load all yaml files to verify syntax.
#   detect-private-key -> Checks for the existence of private keys.
# 
# black -> formatting linter
# codespell -> typical word mistypes
# flake8 -> common linter
# isort -> sorts imports
# language-formatters-pre-commit-hooks -> makes sure golang, ini, java, kotlin, rust, toml, and yaml files are formatted properly


default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--diff, --color]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell  # See 'setup.cfg' for args

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8  # See 'setup.cfg' for args
        additional_dependencies: [flake8-html, flake8-bugbear, flake8-comprehensions]
        args: [--format=html, --htmldir=.report-flake]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile, black]

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
        exclude: .github/workflows/.*\.yml$
    -   id: pretty-format-ini
        args: [--autofix]
