name: Python package

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.x]

        steps:
        -   name: Check out the Repo
            uses: actions/checkout@v3

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
                architecture: x64

        -   name: Print out python version for debugging
            run: |
                pwd
                python -V

        -   name: Install Dev Requirements
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements_dev.txt
                mkdir .reports

        -   name: Lint with flake8
            run: |
                python -m flake8 . --format=html --htmldir=.reports/flake

        -   name: Test with Tox
            run: |
                python -m tox --result-json=.reports/tox.json --html .reports/tox.html
            if: always()

        -   name: Archive flake8 and Tox Results
            uses: actions/upload-artifact@v3
            if: ${{ failure() }}
            with:
                name: flake-and-tox-reports
                path: .reports/
