name: Python package

on: [push]

jobs:
    flake8:
        name: Static Analysis
        strategy:
            matrix:
                os: [ubuntu-20.04, windows-2022]
        runs-on: ${{ matrix.os }}

        steps:
        -   name: Check out the Repo
            uses: actions/checkout@v3

        -   name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'
                architecture: x64

        -   name: Install Dev Requirements
            run: |
                python -V
                python -m pip install --upgrade pip
                python -m pip install -r requirements_dev.txt

        -   name: Lint with flake8
            run: |
                python -m flake8 . --format=html --htmldir=.report-flake

        -   name: Archive flake8 Results
            uses: actions/upload-artifact@v3
            #if: ${{ failure() }}
            with:
                name: flake-report
                path: .report-flake
    tox:
        name: Test
        
        strategy:
            matrix:
                os: [ubuntu-20.04, windows-2022]
        runs-on: ${{ matrix.os }}

        steps:
        -   name: Check out the Repo
            uses: actions/checkout@v3

        -   name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'
                architecture: x64

        -   name: Install Dev Requirements
            run: |
                python -V
                python -m pip install --upgrade pip
                python -m pip install -r requirements_dev.txt

        -   name: Test with Tox
            run: |
                python -m tox --result-json=.report-tox.json --html .report-tox.html

        -   name: Archive Tox Results
            uses: actions/upload-artifact@v3
            #if: ${{ failure() }}
            with:
                name: tox-report
                path: .report-tox*
